[[permission]]
identifier = "allow-all"
description = "Allows all zenith-ide core commands"
commands.allow = [
    "get_file_tree",
    "read_file",
    "write_file",
    "get_git_status",
    "run_diagnostics",
    "run_compiler",
    "search_file_names",
    "search_in_files",
    "get_file_symbols",
    "terminal_create",
    "terminal_write",
    "terminal_resize",
    "terminal_kill"
]
