[[permission]]
identifier = "allow-all"
description = "Permite acesso a todos os comandos da Zenith IDE"
platforms = ["windows"]
commands.allow = [
  "get_file_tree",
  "read_file",
  "write_file",
  "run_compiler",
  "pick_file",
  "pick_folder",
  "pick_save_path",
  "terminal_create",
  "terminal_write",
  "terminal_resize",
  "terminal_kill",
  "greet"
]
